<?php

namespace Supra\Controller\Pages\Configuration;

use Supra\Controller\Pages\BlockControllerCollection;
use Supra\Loader\Loader;
use Supra\Configuration\ConfigurationInterface;

/**
 * BlockControllerGroupConfiguration
 *
 * @author Dmitry Polovka <dmitry.polovka@videinfra.com>
 */
class BlockControllerGroupConfiguration implements ConfigurationInterface
{

	/**
	 * Autogenerated from Group title if isn't set manually
	 * @var string
	 */
	public $id;

	/**
	 * @var string
	 */
	public $title;

	/**
	 * @var boolean
	 */
	public $default = false;

	/**
	 * @{inheritDoc}
	 */
	public function configure()
	{
		BlockControllerCollection::getInstance()
				->addGroupConfiguration($this);
	}

}