<?php

namespace Supra\Router;

use Supra\Tests\TestCase,
		Supra\Controller\FrontController,
		Supra\Router;

/**
 * Test class for UriRouter.
 * Generated by PHPUnit on 2011-10-18 at 16:09:17.
 */
class UriRouterTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Router\UriRouter
	 */
	protected $root;
	/**
	 * @var Router\UriRouter
	 */
	protected $q;
	/**
	 * @var Router\UriRouter
	 */
	protected $qwerty;
	/**
	 * @var Router\UriRouter
	 */
	protected $quertyAbc;

	protected function setUp()
	{
		$this->root = new Router\UriRouter();
		$this->root->setPath('/');
		$this->q = new Router\UriRouter();
		$this->q->setPath('/q');
		$this->qwerty = new Router\UriRouter();
		$this->qwerty->setPath('/qwerty/');
		$this->quertyAbc = new Router\UriRouter();
		$this->quertyAbc->setPath('qwerty/abc');
	}

	function testCompareRouters()
	{
		self::assertLessThan($this->q->getPriority(), $this->root->getPriority());
		self::assertEquals($this->qwerty->getPriority(), $this->q->getPriority());
		self::assertLessThan($this->quertyAbc->getPriority(), $this->q->getPriority());
		self::assertLessThan($this->quertyAbc->getPriority(), $this->qwerty->getPriority());
		self::assertLessThan($this->quertyAbc->getPriority(), $this->root->getPriority());
		
		$this->qwerty->setPriorityDiff(Router\UriRouter::PRIORITY_HIGH);
		self::assertLessThan($this->qwerty->getPriority(), $this->q->getPriority());
	}
}
