<?php

namespace Supra\Tests\Event;

use Supra\Event\EventArgs;

/**
 * Test class for EventArgs.
 * Generated by PHPUnit on 2011-10-27 at 18:21:08.
 */
class EventArgsTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var EventArgs
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new EventArgs;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @todo Implement testGetEmptyInstance().
	 */
	public function testGetEmptyInstance()
	{
		$emptyInstance = EventArgs::getEmptyInstance();
		self::assertInstanceOf('Supra\Event\EventArgs', $emptyInstance);
		
		$emptyInstance2 = EventArgs::getEmptyInstance();
		self::assertTrue($emptyInstance === $emptyInstance2);
		
		$newInstance = new EventArgs();
		self::assertFalse($emptyInstance === $newInstance);
	}

}
