<?php

namespace Supra\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SupraControllerPagesEntityLayoutProxy extends \Supra\Controller\Pages\Entity\Layout implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setFile($file)
    {
        $this->_load();
        return parent::setFile($file);
    }

    public function getFile()
    {
        $this->_load();
        return parent::getFile();
    }

    public function getPlaceHolders()
    {
        $this->_load();
        return parent::getPlaceHolders();
    }

    public function addPlaceHolder(\Supra\Controller\Pages\Entity\LayoutPlaceHolder $placeHolder)
    {
        $this->_load();
        return parent::addPlaceHolder($placeHolder);
    }

    public function getPlaceHolderNames()
    {
        $this->_load();
        return parent::getPlaceHolderNames();
    }

    public function getContent()
    {
        $this->_load();
        return parent::getContent();
    }

    public function getRepository()
    {
        $this->_load();
        return parent::getRepository();
    }

    public function getProperty($name)
    {
        $this->_load();
        return parent::getProperty($name);
    }

    public function getDiscriminator()
    {
        $this->_load();
        return parent::getDiscriminator();
    }

    public function matchDiscriminator(\Supra\Controller\Pages\Entity\Abstraction\Entity $object, $strict = true)
    {
        $this->_load();
        return parent::matchDiscriminator($object, $strict);
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'file', 'placeHolders');
    }
}