<?php

namespace Supra\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SupraControllerPagesBlockAbstractionProxy extends \Supra\Controller\Pages\BlockAbstraction implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function execute(\Supra\Controller\Request\RequestInterface $request, \Supra\Controller\Response\ResponseInterface $response)
    {
        $this->_load();
        return parent::execute($request, $response);
    }

    public function getResponseObject(\Supra\Controller\Request\RequestInterface $request)
    {
        $this->_load();
        return parent::getResponseObject($request);
    }

    public function getRequest()
    {
        $this->_load();
        return parent::getRequest();
    }

    public function getResponse()
    {
        $this->_load();
        return parent::getResponse();
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array();
    }
}