<?php

namespace Supra\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SupraControllerPagesEntityAbstractionBlockProxy extends \Supra\Controller\Pages\Entity\Abstraction\Block implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function getLocked()
    {
        $this->_load();
        return parent::getLocked();
    }

    public function getPlaceHolder()
    {
        $this->_load();
        return parent::getPlaceHolder();
    }

    public function setPlaceHolder(\Supra\Controller\Pages\Entity\Abstraction\PlaceHolder $placeHolder)
    {
        $this->_load();
        return parent::setPlaceHolder($placeHolder);
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getComponent()
    {
        $this->_load();
        return parent::getComponent();
    }

    public function setComponent($component)
    {
        $this->_load();
        return parent::setComponent($component);
    }

    public function getPosition()
    {
        $this->_load();
        return parent::getPosition();
    }

    public function setPosition($position)
    {
        $this->_load();
        return parent::setPosition($position);
    }

    public function addBlockProperty(\Supra\Controller\Pages\Entity\Abstraction\BlockProperty $blockProperty)
    {
        $this->_load();
        return parent::addBlockProperty($blockProperty);
    }

    public function inPlaceHolder(array $placeHolderIds)
    {
        $this->_load();
        return parent::inPlaceHolder($placeHolderIds);
    }

    public function controllerFactory()
    {
        $this->_load();
        return parent::controllerFactory();
    }

    public function setController(\Supra\Controller\Pages\BlockController $blockController)
    {
        $this->_load();
        return parent::setController($blockController);
    }

    public function getController()
    {
        $this->_load();
        return parent::getController();
    }

    public function getProperty($name)
    {
        $this->_load();
        return parent::getProperty($name);
    }

    public function getDiscriminator()
    {
        $this->_load();
        return parent::getDiscriminator();
    }

    public function matchDiscriminator(\Supra\Controller\Pages\Entity\Abstraction\Entity $object, $strict = true)
    {
        $this->_load();
        return parent::matchDiscriminator($object, $strict);
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('id', 'component', 'position', 'locked', 'placeHolder', 'blockProperties');
    }
}