<?php

namespace Supra\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SupraControllerPagesEntityAbstractionPageProxy extends \Supra\Controller\Pages\Entity\Abstraction\Page implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getPlaceHolders()
    {
        $this->__load();
        return parent::getPlaceHolders();
    }

    public function getDataCollection()
    {
        $this->__load();
        return parent::getDataCollection();
    }

    public function getData($locale)
    {
        $this->__load();
        return parent::getData($locale);
    }

    public function setData(\Supra\Controller\Pages\Entity\Abstraction\Data $data)
    {
        $this->__load();
        return parent::setData($data);
    }

    public function removeData($locale)
    {
        $this->__load();
        return parent::removeData($locale);
    }

    public function addPlaceHolder(\Supra\Controller\Pages\Entity\Abstraction\PlaceHolder $placeHolder)
    {
        $this->__load();
        return parent::addPlaceHolder($placeHolder);
    }

    public function isBlockPropertyEditable(\Supra\Controller\Pages\Entity\BlockProperty $blockProperty)
    {
        $this->__load();
        return parent::isBlockPropertyEditable($blockProperty);
    }

    public function isBlockEditable(\Supra\Controller\Pages\Entity\Abstraction\Block $block)
    {
        $this->__load();
        return parent::isBlockEditable($block);
    }

    public function isBlockManageable(\Supra\Controller\Pages\Entity\Abstraction\Block $block)
    {
        $this->__load();
        return parent::isBlockManageable($block);
    }

    public function isPlaceHolderEditable(\Supra\Controller\Pages\Entity\Abstraction\PlaceHolder $placeHolder)
    {
        $this->__load();
        return parent::isPlaceHolderEditable($placeHolder);
    }

    public function getTemplateHierarchy()
    {
        $this->__load();
        return parent::getTemplateHierarchy();
    }

    public function getRepository()
    {
        $this->__load();
        return parent::getRepository();
    }

    public function getProperty($name)
    {
        $this->__load();
        return parent::getProperty($name);
    }

    public function getDiscriminator()
    {
        $this->__load();
        return parent::getDiscriminator();
    }

    public function matchDiscriminator(\Supra\Controller\Pages\Entity\Abstraction\Entity $object, $strict = true)
    {
        $this->__load();
        return parent::matchDiscriminator($object, $strict);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function equals(\Supra\Controller\Pages\Entity\Abstraction\Entity $entity)
    {
        $this->__load();
        return parent::equals($entity);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'placeHolders', 'depth');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}