<?php

namespace Supra\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SupraControllerPagesEntityPageProxy extends \Supra\Controller\Pages\Entity\Page implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function setTemplate(\Supra\Controller\Pages\Entity\Template $template)
    {
        $this->_load();
        return parent::setTemplate($template);
    }

    public function getTemplate()
    {
        $this->_load();
        return parent::getTemplate();
    }

    public function setParent(\Supra\Controller\Pages\Entity\Abstraction\Page $page = NULL)
    {
        $this->_load();
        return parent::setParent($page);
    }

    public function getTemplates()
    {
        $this->_load();
        return parent::getTemplates();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getParent()
    {
        $this->_load();
        return parent::getParent();
    }

    public function getChildren()
    {
        $this->_load();
        return parent::getChildren();
    }

    public function getPlaceHolders()
    {
        $this->_load();
        return parent::getPlaceHolders();
    }

    public function getDataCollection()
    {
        $this->_load();
        return parent::getDataCollection();
    }

    public function getData($locale)
    {
        $this->_load();
        return parent::getData($locale);
    }

    public function setData(\Supra\Controller\Pages\Entity\Abstraction\Data $data)
    {
        $this->_load();
        return parent::setData($data);
    }

    public function removeData($locale)
    {
        $this->_load();
        return parent::removeData($locale);
    }

    public function addPlaceHolder(\Supra\Controller\Pages\Entity\Abstraction\PlaceHolder $placeHolder)
    {
        $this->_load();
        return parent::addPlaceHolder($placeHolder);
    }

    public function getProperty($name)
    {
        $this->_load();
        return parent::getProperty($name);
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('data', 'template', 'children', 'parent', 'placeHolders', 'id', 'depth');
    }
}