<?php

namespace Supra\Tests\NestedSet\Node;

use Supra\Tests\NestedSet\Fixture;
use Supra\NestedSet\ArrayRepository;
use Supra\NestedSet\Node\ArrayNode;
use Supra\Tests\NestedSet\Model;

/**
 * Test class for ArrayNode.
 * Generated by PHPUnit on 2010-08-10 at 14:41:40.
 */
class ArrayNodeTest extends NodeTest
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$rep = Fixture\ArrayNestedSet::foodTree();
		$this->repository = $rep;
		
		parent::setUp();
	}

	/**
	 */
	public function testSetRepository()
	{
		$rep = new ArrayRepository();
		$this->food->setRepository($rep);
		self::assertEquals($rep, $this->food->getRepository());
	}

	/**
	 */
	public function testAddChild()
	{
		$badBeef = $this->repository->createNode('Bad Beef');
		$this->beef->addChild($badBeef);

		$output = $this->repository->drawTree();

		$expected = <<<DOC
(1; 20) 0 Food
  (2; 11) 1 Fruit
    (3; 6) 2 Red
      (4; 5) 3 Cherry
    (7; 10) 2 Yellow
      (8; 9) 3 Banana
  (12; 19) 1 Meat
    (13; 16) 2 Beef
      (14; 15) 3 Bad Beef
    (17; 18) 2 Pork

DOC;

		self::assertEquals($expected, $output);
	}
	
	/**
	 * Persist the created node by adding it to the repository
	 * @param Model\Product $product
	 */
	protected function persist(Model\Product $product)
	{
		$product->createArrayNestedSetNode();
		$this->repository->add($product);
	}
}
