<?php

namespace Doctrine\Tests\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DoctrineTestsModelsCMSCmsUserProxy extends \Doctrine\Tests\Models\CMS\CmsUser implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function getUsername()
    {
        $this->_load();
        return parent::getUsername();
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function addPhonenumber(\Doctrine\Tests\Models\CMS\CmsPhonenumber $phone)
    {
        $this->_load();
        return parent::addPhonenumber($phone);
    }

    public function getPhonenumbers()
    {
        $this->_load();
        return parent::getPhonenumbers();
    }

    public function addArticle(\Doctrine\Tests\Models\CMS\CmsArticle $article)
    {
        $this->_load();
        return parent::addArticle($article);
    }

    public function addGroup(\Doctrine\Tests\Models\CMS\CmsGroup $group)
    {
        $this->_load();
        return parent::addGroup($group);
    }

    public function getGroups()
    {
        $this->_load();
        return parent::getGroups();
    }

    public function removePhonenumber($index)
    {
        $this->_load();
        return parent::removePhonenumber($index);
    }

    public function getAddress()
    {
        $this->_load();
        return parent::getAddress();
    }

    public function setAddress(\Doctrine\Tests\Models\CMS\CmsAddress $address)
    {
        $this->_load();
        return parent::setAddress($address);
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('id', 'status', 'username', 'name', 'phonenumbers', 'articles', 'address', 'groups');
    }
}