<?php

namespace Doctrine\Tests\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DoctrineTestsORMFunctionalLifecycleCallbackTestEntityProxy extends \Doctrine\Tests\ORM\Functional\LifecycleCallbackTestEntity implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function doStuffOnPrePersist()
    {
        $this->_load();
        return parent::doStuffOnPrePersist();
    }

    public function doStuffOnPostPersist()
    {
        $this->_load();
        return parent::doStuffOnPostPersist();
    }

    public function doStuffOnPostLoad()
    {
        $this->_load();
        return parent::doStuffOnPostLoad();
    }

    public function doStuffOnPreUpdate()
    {
        $this->_load();
        return parent::doStuffOnPreUpdate();
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('id', 'value', 'cascader');
    }
}