<?php

namespace Doctrine\Tests\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DoctrineTestsORMFunctionalMultiSelfReferenceProxy extends \Doctrine\Tests\ORM\Functional\MultiSelfReference implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setOther1($other1)
    {
        $this->_load();
        return parent::setOther1($other1);
    }

    public function getOther1()
    {
        $this->_load();
        return parent::getOther1();
    }

    public function setOther2($other2)
    {
        $this->_load();
        return parent::setOther2($other2);
    }

    public function getOther2()
    {
        $this->_load();
        return parent::getOther2();
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('id', 'other1', 'other2');
    }
}