<?php

namespace Doctrine\Tests\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DoctrineTestsModelsCMSCmsAddressProxy extends \Doctrine\Tests\Models\CMS\CmsAddress implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getUser()
    {
        $this->_load();
        return parent::getUser();
    }

    public function getCountry()
    {
        $this->_load();
        return parent::getCountry();
    }

    public function getZipCode()
    {
        $this->_load();
        return parent::getZipCode();
    }

    public function getCity()
    {
        $this->_load();
        return parent::getCity();
    }

    public function setUser(\Doctrine\Tests\Models\CMS\CmsUser $user)
    {
        $this->_load();
        return parent::setUser($user);
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('id', 'country', 'zip', 'city', 'user');
    }
}