<?php

/*
 * Copyright (C) SiteSupra SIA, Riga, Latvia, 2015
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */

namespace Supra\Package\Cms\Entity;

/**
 * @Entity
 * @Table(name="file_path")
 */
class FilePath extends Abstraction\Entity
{
	/**
	 * @Column(type="string", name="system_path", nullable=true)
	 * 
	 * @var integer
	 */
	protected $systemPath;

	/**
	 * @Column(type="string", name="web_path", nullable=true)
	 * 
	 * @var integer
	 */
	protected $webPath;

	/**
	 * Entity autogenerated ID is overrided, 
	 * so the file and file path IDs would be the same
	 * 
	 * @param string $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * Returns file system path
	 * 
	 * @return string 
	 */
	public function getSystemPath()
	{
		return $this->systemPath;
	}

	/**
	 * System path setter
	 * 
	 * @param string $systemPath
	 */
	public function setSystemPath($systemPath)
	{
		$this->systemPath = $systemPath;
	}

	/**
	 * Returns file web path
	 * 
	 * @return string
	 */
	public function getWebPath()
	{
		return $this->webPath;
	}

	/**
	 * Web path setter
	 * 
	 * @param string $webPath
	 */
	public function setWebPath($webPath)
	{
		$this->webPath = $webPath;
	}
}