<?php

namespace Supra\Controller\Pages\Configuration;

use Supra\Controller\Pages\BlockControllerCollection;
use Supra\Loader\Loader;
use Supra\Configuration\ConfigurationInterface;
use Supra\Configuration\ComponentConfiguration;

/**
 * Block configuration class
 * @author Dmitry Polovka <dmitry.polovka@videinfra.com>
 */
class BlockControllerConfiguration extends ComponentConfiguration
{

	/**
	 * Group id 
	 * @var string
	 */
	public $groupId = null;

	/**
	 * @var string
	 */
	public $description;

	/**
	 * Local icon path
	 * @var string
	 */
	public $icon;

	/**
	 * Full icon web path, autogenerated if empty
	 * @var string
	 */
	public $iconWebPath = '/cms/lib/supra/img/blocks/icons-items/default.png';

	/**
	 * CMS classname for the block
	 * @var string
	 */
	public $cmsClassname = 'Editable';

	/**
	 * Block controller class name
	 * @var string
	 */
	public $controllerClass;

	/**
	 * Should be block hidden from block menu or not
	 * @var boolean
	 */
	public $hidden = false;

	/**
	 * Can only one block exist on a page
	 * @var boolean
	 */
	public $unique = false;

	/**
	 * Block HTML description
	 * @var string
	 */
	public $html;

	/**
	 * Cache implementation
	 * @var BlockControllerCacheConfiguration
	 */
	public $cache;

	/**
	 * @var array of block properties
	 */
	public $properties = array();

	/**
	 * @var array of block property groups
	 */
	public $propertyGroups = array();

	/**
	 * Adds block configuration to block controller collection
	 */
	public function configure()
	{
		if (empty($this->class)) {
			\Log::warn("Configuration property BlockControllerConfiguration::controllerClass deprecated; use class instead.");
			$this->class = $this->controllerClass;
		}

		if (empty($this->id)) {
			$id = $this->prepareClassId($this->class);
			$this->id = $id;
		}

		if ( ! empty($this->icon)) {
			$this->iconWebPath = $this->getIconWebPath($this->icon);
		}

		$this->processProperties();
		$this->processPropertyGroups();

		BlockControllerCollection::getInstance()
				->addBlockConfiguration($this);

		parent::configure();
	}

	protected function processPropertyGroups()
	{
		if (is_array($this->propertyGroups) && ! empty($this->propertyGroups)) {
			$propertyGroups = array();

			foreach ($this->propertyGroups as $group) {
				/* @var $group BlockPropertyGroupConfiguration */
				if ($group instanceof BlockPropertyGroupConfiguration) {

					if (isset($propertyGroups[$group->id])) {
						\Log::warn('Property group with id "' . $group->id . '" already exist in property group list. Skipping group. Configuration: ', $group);
						continue;
					}
					if ( ! empty($group->icon)) {
						$group->icon = $this->getIconWebPath($group->icon);
					}

					$propertyGroups[$group->id] = $group;
				} else {
					\Log::warn('Group should be instance of BlockPropertyGroupConfiguration ', $group);
				}
			}

			$this->propertyGroups = array_values($propertyGroups);
		}
	}

	protected function processProperties()
	{
		$class = $this->class;

		// TODO: might be removed later
		if (Loader::classExists($class)) {
			if (method_exists($class, 'getPropertyDefinition')) {
				$editables = (array) $class::getPropertyDefinition();

				foreach ($editables as $name => $editable) {
					/* @var $editable \Supra\Editable\EditableInterface */
					$this->properties[] = $property = new BlockPropertyConfiguration();
					$property->fillFromEditable($editable, $name);
				}
			}
		}

		// generating new icon path for SelectVisual
		if (is_array($this->properties)) {

			foreach ($this->properties as $property) {
				if ( ! $property->editableInstance instanceof \Supra\Editable\SelectVisual) {
					continue;
				}

				$values = array();

				foreach ($property->values as $value) {
					if (empty($value['icon'])) {
						continue;
					}

					$value['icon'] = $this->getIconWebPath($value['icon']);

					$values[] = $value;
				}

				$property->editableInstance->setValues($values);
			}
		}
	}

	/**
	 * Return icon webpath
	 * @return string
	 */
	private function getIconWebPath($icon = null)
	{
		if (strpos($icon, '/') === 0 || empty($icon)) {
			return $icon;
		}

		$file = Loader::getInstance()->findClassPath($this->class);
		$dir = dirname($file);
		$iconPath = $dir . '/' . $icon;

//		// Disabled for performance
//		if ( ! file_exists($iconPath)) {
//			$iconPath = null;
//		} else

		if (strpos($iconPath, SUPRA_WEBROOT_PATH) !== 0) {
			$iconPath = null;
		} else {
			$iconPath = substr($iconPath, strlen(SUPRA_WEBROOT_PATH) - 1);
		}

		if (DIRECTORY_SEPARATOR === '\\') {
			$iconPath = str_replace(DIRECTORY_SEPARATOR, '/', $iconPath);
		}

		return $iconPath;
	}

	/**
	 * @param string $name
	 * @return BlockPropertyConfiguration
	 */
	public function getProperty($name)
	{
		foreach ($this->properties as $property) {
			/* @var $property BlockPropertyConfiguration */
			if ($property->name === $name) {
				return $property;
			}
		}
	}

	protected function prepareClassId($className)
	{
		return trim(str_replace('\\', '_', $className));
	}

}
